
// src/lib/ports.ts

export interface Port {
  name: string;
  unlocode: string;
  country: string;
  type: 'port' | 'airport';
}

export const portsAndAirports: Port[] = [
  // Principais Portos Brasileiros
  { name: 'Santos', unlocode: 'BRSSZ', country: 'BR', type: 'port' },
  { name: 'Paranaguá', unlocode: 'BRPNG', country: 'BR', type: 'port' },
  { name: 'Itajaí', unlocode: 'BRITJ', country: 'BR', type: 'port' },
  { name: 'Navegantes', unlocode: 'BRNVT', country: 'BR', type: 'port' },
  { name: 'Rio Grande', unlocode: 'BRRIG', country: 'BR', type: 'port' },
  { name: 'Itapoá', unlocode: 'BRIOA', country: 'BR', type: 'port' },
  { name: 'Suape', unlocode: 'BRSUA', country: 'BR', type: 'port' },
  { name: 'Manaus', unlocode: 'BRMAO', country: 'BR', type: 'port' },
  { name: 'Rio de Janeiro', unlocode: 'BRRIO', country: 'BR', type: 'port' },
  { name: 'Pecém', unlocode: 'BRPEC', country: 'BR', type: 'port' },
  { name: 'Belem', unlocode: 'BRBEL', country: 'BR', type: 'port' },
  { name: 'Fortaleza (Mucuripe)', unlocode: 'BRFOR', country: 'BR', type: 'port' },
  { name: 'Imbituba', unlocode: 'BRIBB', country: 'BR', type: 'port' },
  { name: 'Itaguai ( Ex Sepetiba)', unlocode: 'BRIGI', country: 'BR', type: 'port' },
  { name: 'Itaqui', unlocode: 'BRIQI', country: 'BR', type: 'port' },
  { name: 'Recife', unlocode: 'BRREC', country: 'BR', type: 'port' },
  { name: 'Sao Francisco do Sul', unlocode: 'BRSFS', country: 'BR', type: 'port' },
  { name: 'Vila do Conde', unlocode: 'BRVDC', country: 'BR', type: 'port' },
  { name: 'Vitória', unlocode: 'BRVIX', country: 'BR', type: 'port' },
  
  // Principais Aeroportos Brasileiros
  { name: 'Guarulhos (São Paulo)', unlocode: 'GRU', country: 'BR', type: 'airport' },
  { name: 'Viracopos (Campinas)', unlocode: 'VCP', country: 'BR', type: 'airport' },
  { name: 'Galeão (Rio de Janeiro)', unlocode: 'GIG', country: 'BR', type: 'airport' },
  { name: 'Manaus', unlocode: 'MAO', country: 'BR', type: 'airport' },
  { name: 'Curitiba', unlocode: 'CWB', country: 'BR', type: 'airport' },
  
  // Principais Portos Mundiais
  { name: 'Shanghai', unlocode: 'CNSHA', country: 'CN', type: 'port' },
  { name: 'Singapore', unlocode: 'SGSIN', country: 'SG', type: 'port' },
  { name: 'Ningbo-Zhoushan', unlocode: 'CNNGB', country: 'CN', type: 'port' },
  { name: 'Shenzhen', unlocode: 'CNSZX', country: 'CN', type: 'port' },
  { name: 'Guangzhou', unlocode: 'CNCAN', country: 'CN', type: 'port' },
  { name: 'Qingdao', unlocode: 'CNTAO', country: 'CN', type: 'port' },
  { name: 'Busan', unlocode: 'KRPUS', country: 'KR', type: 'port' },
  { name: 'Tianjin', unlocode: 'CNTSN', country: 'CN', type: 'port' },
  { name: 'Hong Kong', unlocode: 'HKHKG', country: 'HK', type: 'port' },
  { name: 'Rotterdam', unlocode: 'NLRTM', country: 'NL', type: 'port' },
  { name: 'Antwerp', unlocode: 'BEANR', country: 'BE', type: 'port' },
  { name: 'Hamburg', unlocode: 'DEHAM', country: 'DE', type: 'port' },
  { name: 'Los Angeles', unlocode: 'USLAX', country: 'US', type: 'port' },
  { name: 'Long Beach', unlocode: 'USLGB', country: 'US', type: 'port' },
  { name: 'New York/New Jersey', unlocode: 'USNYC', country: 'US', type: 'port' },
  { name: 'Jebel Ali (Dubai)', unlocode: 'AEJEA', country: 'AE', type: 'port' },
  { name: 'Valencia', unlocode: 'ESVLC', country: 'ES', type: 'port' },
  { name: 'Algeciras', unlocode: 'ESALG', country: 'ES', type: 'port' },
  { name: 'Piraeus', unlocode: 'GRPIR', country: 'GR', type: 'port' },
  { name: 'Genoa', unlocode: 'ITGOA', country: 'IT', type: 'port' },
  { name: 'Le Havre', unlocode: 'FRLEH', country: 'FR', type: 'port' },
  { name: 'Felixstowe', unlocode: 'GBFXT', country: 'GB', type: 'port' },
  { name: 'Bremerhaven', unlocode: 'DEBRV', country: 'DE', type: 'port' },
  { name: 'Colon', unlocode: 'PAONX', country: 'PA', type: 'port' },
  { name: 'Manzanillo', unlocode: 'PAMIT', country: 'PA', type: 'port' },
  { name: 'Cartagena', unlocode: 'COCTG', country: 'CO', type: 'port' },
  { name: 'Veracruz', unlocode: 'MXVER', country: 'MX', type: 'port' },
  { name: 'Callao', unlocode: 'PECLL', country: 'PE', type: 'port' },
  { name: 'San Antonio', unlocode: 'CLSAI', country: 'CL', type: 'port' },
  { name: 'Buenos Aires', unlocode: 'ARBUE', country: 'AR', type: 'port' },
  { name: 'Montevideo', unlocode: 'UYMVD', country: 'UY', type: 'port' },
  { name: 'Ajman', unlocode: 'AEAJM', country: 'AE', type: 'port' },
  { name: 'Abu Dhabi', unlocode: 'AEAUH', country: 'AE', type: 'port' },
  { name: 'Das Island', unlocode: 'AEDAS', country: 'AE', type: 'port' },
  { name: 'Dubai', unlocode: 'AEDXB', country: 'AE', type: 'port' },
  { name: 'Fateh Terminal', unlocode: 'AEFAT', country: 'AE', type: 'port' },
  { name: 'Fujairah', unlocode: 'AEFJR', country: 'AE', type: 'port' },
  { name: 'Mussafah', unlocode: 'AEFMZ', country: 'AE', type: 'port' },
  { name: 'Hamriyah', unlocode: 'AEHAM', country: 'AE', type: 'port' },
  { name: 'Hamriya Free Zone Port', unlocode: 'AEHZP', country: 'AE', type: 'port' },
  { name: 'Port Khalifa', unlocode: 'AEKHL', country: 'AE', type: 'port' },
  { name: 'Khor Fakkan', unlocode: 'AEKLF', country: 'AE', type: 'port' },
  { name: 'Mina Saqr', unlocode: 'AEMSA', country: 'AE', type: 'port' },
  { name: 'Mina Zayed', unlocode: 'AEMZD', country: 'AE', type: 'port' },
  { name: 'Ras Al Khaimah', unlocode: 'AERKT', country: 'AE', type: 'port' },
  { name: 'Ruwais', unlocode: 'AERUW', country: 'AE', type: 'port' },
  { name: 'Sharjah', unlocode: 'AESHJ', country: 'AE', type: 'port' },
  { name: 'Port Khalid', unlocode: 'AEUAE', country: 'AE', type: 'port' },
  { name: 'Road Bay', unlocode: 'AIRBY', country: 'AI', type: 'port' },
  { name: 'Durres', unlocode: 'ALDRZ', country: 'AL', type: 'port' },
  { name: 'Bonaire', unlocode: 'ANBON', country: 'AN', type: 'port' },
  { name: 'Curacao', unlocode: 'ANCUR', country: 'AN', type: 'port' },
  { name: 'St Eustatius', unlocode: 'ANEUX', country: 'AN', type: 'port' },
  { name: 'Galis Bay', unlocode: 'ANGES', country: 'AN', type: 'port' },
  { name: 'Kralendijk', unlocode: 'ANKRA', country: 'AN', type: 'port' },
  { name: 'Philipsburg', unlocode: 'ANPHI', country: 'AN', type: 'port' },
  { name: 'St. Maarten', unlocode: 'ANSXM', country: 'AN', type: 'port' },
  { name: 'Ambriz', unlocode: 'AOAZZ', country: 'AO', type: 'port' },
  { name: 'Cabinda', unlocode: 'AOCAB', country: 'AO', type: 'port' },
  { name: 'Dalia Terminal', unlocode: 'AODAL', country: 'AO', type: 'port' },
  { name: 'Luanda', unlocode: 'AOLAD', country: 'AO', type: 'port' },
  { name: 'Lobito', unlocode: 'AOLOB', country: 'AO', type: 'port' },
  { name: 'Malongo', unlocode: 'AOMAL', country: 'AO', type: 'port' },
  { name: 'Mossamedes (Namibe)', unlocode: 'AOMSZ', country: 'AO', type: 'port' },
  { name: 'Palanca', unlocode: 'AOPAT', country: 'AO', type: 'port' },
  { name: 'Porto Amboim', unlocode: 'AOPBM', country: 'AO', type: 'port' },
  { name: 'Soyo', unlocode: 'AOSZA', country: 'AO', type: 'port' },
  { name: 'Kizomba B', unlocode: 'AO002', country: 'AO', type: 'port' },
  { name: 'Porto Palmer', unlocode: 'AQPLM', country: 'AQ', type: 'port' },
  { name: 'Puerto Acevedo', unlocode: 'ARAVD', country: 'AR', type: 'port' },
  { name: 'Belén de Escobar', unlocode: 'ARBDE', country: 'AR', type: 'port' },
  { name: 'Bahia Blanca', unlocode: 'ARBHI', country: 'AR', type: 'port' },
  { name: 'Barranqueras', unlocode: 'ARBQS', country: 'AR', type: 'port' },
  { name: 'Caleta Cordova', unlocode: 'ARCLC', country: 'AR', type: 'port' },
  { name: 'Campana', unlocode: 'ARCMP', country: 'AR', type: 'port' },
  { name: 'Corrientes', unlocode: 'ARCNQ', country: 'AR', type: 'port' },
  { name: 'Concepcion Del Uruguay', unlocode: 'ARCOU', country: 'AR', type: 'port' },
  { name: 'San Martin', unlocode: 'ARCPC', country: 'AR', type: 'port' },
  { name: 'Comodoro Rivadavia', unlocode: 'ARCRD', country: 'AR', type: 'port' },
  { name: 'Caleta Olivia', unlocode: 'ARCVI', country: 'AR', type: 'port' },
  { name: 'Delta Dock-Lima', unlocode: 'ARDDL', country: 'AR', type: 'port' },
  { name: 'Del Guazu', unlocode: 'ARDGU', country: 'AR', type: 'port' },
  { name: 'Diamante', unlocode: 'ARDME', country: 'AR', type: 'port' },
  { name: 'Gualeguaychu', unlocode: 'ARGHU', country: 'AR', type: 'port' },
  { name: 'Ingeniero Buitrago', unlocode: 'ARIBO', country: 'AR', type: 'port' },
  { name: 'Ibicuy', unlocode: 'ARIBY', country: 'AR', type: 'port' },
  { name: 'Ingenieiro White/Bahia Blanca', unlocode: 'ARINW', country: 'AR', type: 'port' },
  { name: 'Lima', unlocode: 'ARLIM', country: 'AR', type: 'port' },
  { name: 'La Plata', unlocode: 'ARLPG', country: 'AR', type: 'port' },
  { name: 'Puerto Las Palmas', unlocode: 'ARLPS', country: 'AR', type: 'port' },
  { name: 'Mar Del Plata', unlocode: 'ARMDQ', country: 'AR', type: 'port' },
  { name: 'Necochea (Quequen)', unlocode: 'ARNEC', country: 'AR', type: 'port' },
  { name: 'Santo Antonio - Oeste', unlocode: 'AROES', country: 'AR', type: 'port' },
  { name: 'Pto Alumbrera', unlocode: 'ARPAL', country: 'AR', type: 'port' },
  { name: 'Puerto Galvan', unlocode: 'ARPGV', country: 'AR', type: 'port' },
  { name: 'Punta Loyola', unlocode: 'ARPLO', country: 'AR', type: 'port' },
  { name: 'Puerto Madryn', unlocode: 'ARPMY', country: 'AR', type: 'port' },
  { name: 'Punta Quilla', unlocode: 'ARPQU', country: 'AR', type: 'port' },
  { name: 'Parana', unlocode: 'ARPRA', country: 'AR', type: 'port' },
  { name: 'Puerto Rosales', unlocode: 'ARPRS', country: 'AR', type: 'port' },
  { name: 'Puerto Deseado', unlocode: 'ARPUD', country: 'AR', type: 'port' },
  { name: 'Parana Guazu', unlocode: 'ARQBR', country: 'AR', type: 'port' },
  { name: 'Ramallo', unlocode: 'ARRAM', country: 'AR', type: 'port' },
  { name: 'Ingeniero Rocca', unlocode: 'ARROC', country: 'AR', type: 'port' },
  { name: 'Rosario', unlocode: 'ARROS', country: 'AR', type: 'port' },
  { name: 'Santa Cruz', unlocode: 'ARRZA', country: 'AR', type: 'port' },
  { name: 'San Antonio - Este', unlocode: 'ARSAE', country: 'AR', type: 'port' },
  { name: 'Santa Fe', unlocode: 'ARSFN', country: 'AR', type: 'port' },
  { name: 'La Paz', unlocode: 'ARSLA', country: 'AR', type: 'port' },
  { name: 'San Lorenzo', unlocode: 'ARSLO', country: 'AR', type: 'port' },
  { name: 'San Nicolas', unlocode: 'ARSNS', country: 'AR', type: 'port' },
  { name: 'San Pedro', unlocode: 'ARSPD', country: 'AR', type: 'port' },
  { name: 'San Julian', unlocode: 'ARULA', country: 'AR', type: 'port' },
  { name: 'Ushuaia', unlocode: 'ARUSH', country: 'AR', type: 'port' },
  { name: 'Villa Constitucion', unlocode: 'ARVCN', country: 'AR', type: 'port' },
  { name: 'Zarate', unlocode: 'ARZAE', country: 'AR', type: 'port' },
  { name: 'Arroyo Seco', unlocode: 'AR007', country: 'AR', type: 'port' },
  { name: 'Punta Alvear', unlocode: 'AR008', country: 'AR', type: 'port' },
  { name: 'Rio Cullen', unlocode: 'AR020', country: 'AR', type: 'port' },
  { name: 'Dock Sud', unlocode: 'AR024', country: 'AR', type: 'port' },
  { name: 'Pago Pago', unlocode: 'ASPPG', country: 'AS', type: 'port' },
  { name: 'Perth', unlocode: 'ASPTH', country: 'AS', type: 'port' },
  { name: 'Laminaria', unlocode: 'AS001', country: 'AS', type: 'port' },
  { name: 'Viena (Wien)', unlocode: 'ATVIE', country: 'AT', type: 'port' },
  { name: 'Abbot Point', unlocode: 'AUABP', country: 'AU', type: 'port' },
  { name: 'Adelaide', unlocode: 'AUADL', country: 'AU', type: 'port' },
  { name: 'Augusta', unlocode: 'AUAGS', country: 'AU', type: 'port' },
  { name: 'Bing Bong', unlocode: 'AUBBG', country: 'AU', type: 'port' },
  { name: 'Bell Bay', unlocode: 'AUBEL', country: 'AU', type: 'port' },
  { name: 'Broome', unlocode: 'AUBME', country: 'AU', type: 'port' },
  { name: 'Brisbane', unlocode: 'AUBNE', country: 'AU', type: 'port' },
  { name: 'Bunbury', unlocode: 'AUBUY', country: 'AU', type: 'port' },
  { name: 'Burnie', unlocode: 'AUBWT', country: 'AU', type: 'port' },
  { name: 'Dampier', unlocode: 'AUDAM', country: 'AU', type: 'port' },
  { name: 'Darwin', unlocode: 'AUDRW', country: 'AU', type: 'port' },
  { name: 'Esperance', unlocode: 'AUEPR', country: 'AU', type: 'port' },
  { name: 'Fremantle', unlocode: 'AUFRE', country: 'AU', type: 'port' },
  { name: 'Geelong', unlocode: 'AUGEX', country: 'AU', type: 'port' },
  { name: 'Gladstone', unlocode: 'AUGLT', country: 'AU', type: 'port' },
  { name: 'Geraldton', unlocode: 'AUGTT', country: 'AU', type: 'port' },
  { name: 'Hastings', unlocode: 'AUHAS', country: 'AU', type: 'port' },
  { name: 'Hobart', unlocode: 'AUHBA', country: 'AU', type: 'port' },
  { name: 'Hay Point', unlocode: 'AUHPT', country: 'AU', type: 'port' },
  { name: 'Koolan Island', unlocode: 'AUKOI', country: 'AU', type: 'port' },
  { name: 'Kwinana', unlocode: 'AUKWI', country: 'AU', type: 'port' },
  { name: 'Melbourne', unlocode: 'AUMEL', country: 'AU', type: 'port' },
  { name: 'Mackay', unlocode: 'AUMKY', country: 'AU', type: 'port' },
  { name: 'Mourilyan', unlocode: 'AUMOU', country: 'AU', type: 'port' },
  { name: 'Northern Endeavour', unlocode: 'AUNTE', country: 'AU', type: 'port' },
  { name: 'Newcastle (New South Wales)', unlocode: 'AUNTL', country: 'AU', type: 'port' },
  { name: 'Port Arthur', unlocode: 'AUPAU', country: 'AU', type: 'port' },
  { name: 'Port Botany', unlocode: 'AUPBT', country: 'AU', type: 'port' },
  { name: 'Port Giles', unlocode: 'AUPGI', country: 'AU', type: 'port' },
  { name: 'Port Hedland', unlocode: 'AUPHE', country: 'AU', type: 'port' },
  { name: 'Port Kembla', unlocode: 'AUPKL', country: 'AU', type: 'port' },
  { name: 'Port Lincoln', unlocode: 'AUPLO', country: 'AU', type: 'port' },
  { name: 'Port Dalrymple', unlocode: 'AUPTD', country: 'AU', type: 'port' },
  { name: 'Portland', unlocode: 'AUPTJ', country: 'AU', type: 'port' },
  { name: 'Port Alma', unlocode: 'AUPTL', country: 'AU', type: 'port' },
  { name: 'Risdon', unlocode: 'AURDN', country: 'AU', type: 'port' },
  { name: 'Sydney', unlocode: 'AUSYD', country: 'AU', type: 'port' },
  { name: 'Townsville', unlocode: 'AUTSV', country: 'AU', type: 'port' },
  { name: 'Wallaroo', unlocode: 'AUWAL', country: 'AU', type: 'port' },
  { name: 'Weipa', unlocode: 'AUWEI', country: 'AU', type: 'port' },
  { name: 'Westernport', unlocode: 'AUWEP', country: 'AU', type: 'port' },
  { name: 'Whyalla', unlocode: 'AUWYA', country: 'AU', type: 'port' },
  { name: 'Yarraville', unlocode: 'AUYRV', country: 'AU', type: 'port' },
  { name: 'Aruba', unlocode: 'AWAUA', country: 'AW', type: 'port' },
  { name: 'Barcadura', unlocode: 'AWBAR', country: 'AW', type: 'port' },
  { name: 'Oranjestad', unlocode: 'AWORJ', country: 'AW', type: 'port' },
  { name: 'San Nicolas', unlocode: 'AWSNL', country: 'AW', type: 'port' },
  { name: 'Baku', unlocode: 'AZBAK', country: 'AZ', type: 'port' },
  { name: 'Bridgetown', unlocode: 'BBBGI', country: 'BB', type: 'port' },
  { name: 'Chittagong (Chattogram)', unlocode: 'BDCGP', country: 'BD', type: 'port' },
  { name: 'Chalna', unlocode: 'BDCHL', country: 'BD', type: 'port' },
  { name: 'Dhaka', unlocode: 'BDDAC', country: 'BD', type: 'port' },
  { name: 'Mongla', unlocode: 'BDMGL', country: 'BD', type: 'port' },
  { name: 'Payra Port', unlocode: 'BDPAY', country: 'BD', type: 'port' },
  { name: 'Antuerpia (Amberes)', unlocode: 'BEANR', country: 'BE', type: 'port' },
  { name: 'Brugge', unlocode: 'BEBGS', country: 'BE', type: 'port' },
  { name: 'Ghent', unlocode: 'BEGNE', country: 'BE', type: 'port' },
  { name: 'Ostend', unlocode: 'BEOST', country: 'BE', type: 'port' },
  { name: 'Ruisbroek', unlocode: 'BERUI', country: 'BE', type: 'port' },
  { name: 'Sint-Job-in-t-Goor', unlocode: 'BESIG', country: 'BE', type: 'port' },
  { name: 'Zeebrugge', unlocode: 'BEZEE', country: 'BE', type: 'port' },
  { name: 'Zelzate', unlocode: 'BEZEL', country: 'BE', type: 'port' },
  { name: 'Zellik', unlocode: 'BEZLL', country: 'BE', type: 'port' },
  { name: 'Bourgas (Burgas)', unlocode: 'BGBOJ', country: 'BG', type: 'port' },
  { name: 'Varna (Stalin)', unlocode: 'BGVAR', country: 'BG', type: 'port' },
  { name: 'Bahrain', unlocode: 'BHBAH', country: 'BH', type: 'port' },
  { name: 'Al Muharraq', unlocode: 'BHGBQ', country: 'BH', type: 'port' },
  { name: 'Khalifa Bin Salmon Port', unlocode: 'BHKBS', country: 'BH', type: 'port' },
  { name: 'Sitra', unlocode: 'BHSIT', country: 'BH', type: 'port' },
  { name: 'Cotonou', unlocode: 'BJCOO', country: 'BJ', type: 'port' },
  { name: 'Hamilton', unlocode: 'BMBDA', country: 'BM', type: 'port' },
  { name: 'Bermudas', unlocode: 'BMFPT', country: 'BM', type: 'port' },
  { name: 'St Georges', unlocode: 'BMSGE', country: 'BM', type: 'port' },
  { name: 'Lumut', unlocode: 'BNLUM', country: 'BN', type: 'port' },
  { name: 'Muara', unlocode: 'BNMUA', country: 'BN', type: 'port' },
  { name: 'Aguirre', unlocode: 'BO001', country: 'BO', type: 'port' },
  { name: 'Quijarro', unlocode: 'BO002', country: 'BO', type: 'port' },
  { name: 'Terminal de Regência', unlocode: 'BRREL', country: 'BR', type: 'port' },
  { name: 'Sepetiba (Ilha de Jaguanum)', unlocode: 'BR131', country: 'BR', type: 'port' },
  { name: 'São Francisco', unlocode: 'BR134', country: 'BR', type: 'port' },
  { name: 'Cococay', unlocode: 'BSCOC', country: 'BS', type: 'port' },
  { name: 'Freeport', unlocode: 'BSFPO', country: 'BS', type: 'port' },
  { name: 'Nassau', unlocode: 'BSNAS', country: 'BS', type: 'port' },
  { name: 'South Riding Point', unlocode: 'BSSRP', country: 'BS', type: 'port' },
  { name: 'San Salvador', unlocode: 'BSZSA', country: 'BS', type: 'port' },
  { name: 'Minsk', unlocode: 'BYMSQ', country: 'BY', type: 'port' },
  { name: 'Belize', unlocode: 'BZBZE', country: 'BZ', type: 'port' },
  { name: 'Bayside', unlocode: 'CABAS', country: 'CA', type: 'port' },
  { name: 'Bay Bulls', unlocode: 'CABBU', country: 'CA', type: 'port' },
  { name: 'Baie Comeau', unlocode: 'CABCO', country: 'CA', type: 'port' },
  { name: 'Becancour', unlocode: 'CABEC', country: 'CA', type: 'port' },
  { name: 'Bellendune', unlocode: 'CABEL', country: 'CA', type: 'port' },
  { name: 'Calgary', unlocode: 'CACAL', country: 'CA', type: 'port' },
  { name: 'Come By Change', unlocode: 'CACBC', country: 'CA', type: 'port' },
  { name: 'Corner Brook', unlocode: 'CACBK', country: 'CA', type: 'port' },
  { name: 'Churchill', unlocode: 'CACHV', country: 'CA', type: 'port' },
  { name: 'Contrecoeur', unlocode: 'CACOC', country: 'CA', type: 'port' },
  { name: 'Canaport', unlocode: 'CACPT', country: 'CA', type: 'port' },
  { name: 'Crofton', unlocode: 'CACRO', country: 'CA', type: 'port' },
  { name: 'Cote Ste. Catherine', unlocode: 'CACSC', country: 'CA', type: 'port' },
  { name: 'Ducan Bay', unlocode: 'CADCN', country: 'CA', type: 'port' },
  { name: 'Ilha do Fogo', unlocode: 'CAFOG', country: 'CA', type: 'port' },
  { name: 'Grande Anse', unlocode: 'CAGAE', country: 'CA', type: 'port' },
  { name: 'Gros Cacouna', unlocode: 'CAGCA', country: 'CA', type: 'port' },
  { name: 'Georgetown', unlocode: 'CAGGW', country: 'CA', type: 'port' },
  { name: 'Gaspe', unlocode: 'CAGPE', country: 'CA', type: 'port' },
  { name: 'Halifax', unlocode: 'CAHAL', country: 'CA', type: 'port' },
  { name: 'Hamilton', unlocode: 'CAHAM', country: 'CA', type: 'port' },
  { name: 'Hull', unlocode: 'CAHUL', country: 'CA', type: 'port' },
  { name: 'Johnstown', unlocode: 'CAJOH', country: 'CA', type: 'port' },
  { name: 'Kingston', unlocode: 'CAKIN', country: 'CA', type: 'port' },
  { name: 'Kitimat', unlocode: 'CAKTM', country: 'CA', type: 'port' },
  { name: 'Lower Cove', unlocode: 'CALCV', country: 'CA', type: 'port' },
  { name: 'Liverpool', unlocode: 'CALIV', country: 'CA', type: 'port' },
  { name: 'Long Pond', unlocode: 'CALOP', country: 'CA', type: 'port' },
  { name: 'Lunenburg', unlocode: 'CALUN', country: 'CA', type: 'port' },
  { name: 'Montreal', unlocode: 'CAMTR', country: 'CA', type: 'port' },
  { name: 'Nanticoke', unlocode: 'CANAN', country: 'CA', type: 'port' },
  { name: 'Neptune Terminals, BC, Canada', unlocode: 'CANEP', country: 'CA', type: 'port' },
  { name: 'Nanaimo', unlocode: 'CANNO', country: 'CA', type: 'port' },
  { name: 'New Westminster', unlocode: 'CANWE', country: 'CA', type: 'port' },
  { name: 'Argentia', unlocode: 'CANWP', country: 'CA', type: 'port' },
  { name: 'Ocean Falls', unlocode: 'CAOFA', country: 'CA', type: 'port' },
  { name: 'Oshawa', unlocode: 'CAOSH', country: 'CA', type: 'port' },
  { name: 'Port Alice', unlocode: 'CAPAC', country: 'CA', type: 'port' },
  { name: 'Port Alfred', unlocode: 'CAPAF', country: 'CA', type: 'port' },
  { name: 'Port Cartier', unlocode: 'CAPCA', country: 'CA', type: 'port' },
  { name: 'Port Hawkesbury', unlocode: 'CAPHW', country: 'CA', type: 'port' },
  { name: 'Port Arthur', unlocode: 'CAPOA', country: 'CA', type: 'port' },
  { name: 'Prince Rupert', unlocode: 'CAPRR', country: 'CA', type: 'port' },
  { name: 'Pictou', unlocode: 'CAPTO', country: 'CA', type: 'port' },
  { name: 'Point Tupper', unlocode: 'CAPTU', country: 'CA', type: 'port' },
  { name: 'Quebec', unlocode: 'CAQUE', country: 'CA', type: 'port' },
  { name: 'Roberts Bank', unlocode: 'CARBK', country: 'CA', type: 'port' },
  { name: 'Regina, SK', unlocode: 'CAREG', country: 'CA', type: 'port' },
  { name: 'Saskatoon', unlocode: 'CASAK', country: 'CA', type: 'port' },
  { name: 'Sidney', unlocode: 'CASDY', country: 'CA', type: 'port' },
  { name: 'Sept Iles', unlocode: 'CASEI', country: 'CA', type: 'port' },
  { name: 'Sept-Îles (CASEI)', unlocode: 'CASEP', country: 'CA', type: 'port' },
  { name: 'Sheet Harbour', unlocode: 'CASHH', country: 'CA', type: 'port' },
  { name: 'Saint John', unlocode: 'CASJB', country: 'CA', type: 'port' },
  { name: 'St Jonhs', unlocode: 'CASJF', country: 'CA', type: 'port' },
  { name: 'Sarnia', unlocode: 'CASNI', country: 'CA', type: 'port' },
  { name: 'Sorel', unlocode: 'CASOR', country: 'CA', type: 'port' },
  { name: 'Springdale', unlocode: 'CASPD', country: 'CA', type: 'port' },
  { name: 'Squamish', unlocode: 'CASQA', country: 'CA', type: 'port' },
  { name: 'Sault Ste Marie', unlocode: 'CASSM', country: 'CA', type: 'port' },
  { name: 'Stephenville', unlocode: 'CASTV', country: 'CA', type: 'port' },
  { name: 'Summerside', unlocode: 'CASUM', country: 'CA', type: 'port' },
  { name: 'Thunder Bay', unlocode: 'CATHU', country: 'CA', type: 'port' },
  { name: 'Toronto', unlocode: 'CATOR', country: 'CA', type: 'port' },
  { name: 'Trois-Rivières', unlocode: 'CATRR', country: 'CA', type: 'port' },
  { name: 'Three Rivers', unlocode: 'CATTR', country: 'CA', type: 'port' },
  { name: 'Vancouver', unlocode: 'CAVAN', country: 'CA', type: 'port' },
  { name: 'Victoria', unlocode: 'CAVIC', country: 'CA', type: 'port' },
  { name: 'Valleyfield', unlocode: 'CAVLF', country: 'CA', type: 'port' },
  { name: 'Windsor', unlocode: 'CAWND', country: 'CA', type: 'port' },
  { name: 'Chisasibi', unlocode: 'CAYKU', country: 'CA', type: 'port' },
  { name: 'Yarmouth', unlocode: 'CAYRH', country: 'CA', type: 'port' },
  { name: 'Westshore Terminals', unlocode: 'CA100', country: 'CA', type: 'port' },
  { name: 'Ango Ango', unlocode: 'CDANG', country: 'CD', type: 'port' },
  { name: 'Banana', unlocode: 'CDBNW', country: 'CD', type: 'port' },
  { name: 'Boma', unlocode: 'CDBOA', country: 'CD', type: 'port' },
  { name: 'Matadi', unlocode: 'CDMAT', country: 'CD', type: 'port' },
  { name: 'Muanda', unlocode: 'CDMNB', country: 'CD', type: 'port' },
  { name: 'Matadi', unlocode: 'CFMAT', country: 'CF', type: 'port' },
  { name: 'Djeno', unlocode: 'CGBTB', country: 'CG', type: 'port' },
  { name: 'Matadi', unlocode: 'CGMAT', country: 'CG', type: 'port' },
  { name: 'Nkossa', unlocode: 'CGNKO', country: 'CG', type: 'port' },
  { name: 'Pointe Noire', unlocode: 'CGPNR', country: 'CG', type: 'port' },
  { name: 'Basileia', unlocode: 'CHBSL', country: 'CH', type: 'port' },
  { name: 'Abidjan', unlocode: 'CIABJ', country: 'CI', type: 'port' },
  { name: 'Espoir', unlocode: 'CIESP', country: 'CI', type: 'port' },
  { name: 'Mejillones', unlocode: 'CIMJS', country: 'CI', type: 'port' },
  { name: 'San Pedro', unlocode: 'CISPY', country: 'CI', type: 'port' },
  { name: 'Rarotonga', unlocode: 'CKRAR', country: 'CK', type: 'port' },
  { name: 'Antofagasta', unlocode: 'CLANF', country: 'CL', type: 'port' },
  { name: 'Arica', unlocode: 'CLARI', country: 'CL', type: 'port' },
  { name: 'Barquito', unlocode: 'CLBAR', country: 'CL', type: 'port' },
  { name: 'Caleta Patillos', unlocode: 'CLCAL', country: 'CL', type: 'port' },
  { name: 'Calbuco', unlocode: 'CLCBC', country: 'CL', type: 'port' },
  { name: 'Caldera', unlocode: 'CLCLD', country: 'CL', type: 'port' },
  { name: 'Caleta Clarencia', unlocode: 'CLCLR', country: 'CL', type: 'port' },
  { name: 'Coronel', unlocode: 'CLCNL', country: 'CL', type: 'port' },
  { name: 'Cabo Negro', unlocode: 'CLCNX', country: 'CL', type: 'port' },
  { name: 'Caleta Coloso', unlocode: 'CLCOL', country: 'CL', type: 'port' },
  { name: 'Coquimbo', unlocode: 'CLCQQ', country: 'CL', type: 'port' },
  { name: 'Puerto Eden', unlocode: 'CLEDE', country: 'CL', type: 'port' },
  { name: 'Huachipato', unlocode: 'CLHPO', country: 'CL', type: 'port' },
  { name: 'Huasco', unlocode: 'CLHSO', country: 'CL', type: 'port' },
  { name: 'Iquique', unlocode: 'CLIQQ', country: 'CL', type: 'port' },
  { name: 'Los Vilos', unlocode: 'CLLOS', country: 'CL', type: 'port' },
  { name: 'Lirquen', unlocode: 'CLLQN', country: 'CL', type: 'port' },
  { name: 'Las Ventanas', unlocode: 'CLLVS', country: 'CL', type: 'port' },
  { name: 'Michilla', unlocode: 'CLMIC', country: 'CL', type: 'port' },
  { name: 'Mejillones', unlocode: 'CLMJS', country: 'CL', type: 'port' },
  { name: 'Puerto Angamos', unlocode: 'CLPAG', country: 'CL', type: 'port' },
  { name: 'Punta Patache', unlocode: 'CLPAT', country: 'CL', type: 'port' },
  { name: 'Puerto Chacabuco', unlocode: 'CLPCH', country: 'CL', type: 'port' },
  { name: 'Penco', unlocode: 'CLPEO', country: 'CL', type: 'port' },
  { name: 'Puerto Montt', unlocode: 'CLPMC', country: 'CL', type: 'port' },
  { name: 'Patillos', unlocode: 'CLPTI', country: 'CL', type: 'port' },
  { name: 'Punta Chungo', unlocode: 'CLPTP', country: 'CL', type: 'port' },
  { name: 'Punta Arenas', unlocode: 'CLPUQ', country: 'CL', type: 'port' },
  { name: 'Quintero', unlocode: 'CLQTV', country: 'CL', type: 'port' },
  { name: 'San Vicente', unlocode: 'CLSVE', country: 'CL', type: 'port' },
  { name: 'Talcahuano (Concepcion)', unlocode: 'CLTAL', country: 'CL', type: 'port' },
  { name: 'Tocopilla', unlocode: 'CLTOQ', country: 'CL', type: 'port' },
  { name: 'Valparaiso', unlocode: 'CLVAP', country: 'CL', type: 'port' },
  { name: 'Puerto Williams', unlocode: 'CLWPU', country: 'CL', type: 'port' },
  { name: 'Ancud', unlocode: 'CLZUD', country: 'CL', type: 'port' },
  { name: 'Douala', unlocode: 'CMDLA', country: 'CM', type: 'port' },
  { name: 'Kribi', unlocode: 'CMKBI', country: 'CM', type: 'port' },
  { name: 'Terminal de Kole', unlocode: 'CMKOL', country: 'CM', type: 'port' },
  { name: 'Limbe', unlocode: 'CMLIM', country: 'CM', type: 'port' },
  { name: 'Moudi Terminal', unlocode: 'CMMOU', country: 'CM', type: 'port' },

  // Principais Aeroportos Mundiais
  { name: 'Hong Kong Intl', unlocode: 'HKG', country: 'HK', type: 'airport' },
  { name: 'Memphis', unlocode: 'MEM', country: 'US', type: 'airport' },
  { name: 'Shanghai Pudong', unlocode: 'PVG', country: 'CN', type: 'airport' },
  { name: 'Anchorage', unlocode: 'ANC', country: 'US', type: 'airport' },
  { name: 'Incheon (Seoul)', unlocode: 'ICN', country: 'KR', type: 'airport' },
  { name: 'Dubai Intl', unlocode: 'DXB', country: 'AE', type: 'airport' },
  { name: 'Doha', unlocode: 'DOH', country: 'QA', type: 'airport' },
  { name: 'Narita (Tokyo)', unlocode: 'NRT', country: 'JP', type: 'airport' },
  { name: 'Frankfurt', unlocode: 'FRA', country: 'DE', type: 'airport' },
  { name: 'Miami', unlocode: 'MIA', country: 'US', type: 'airport' },
  { name: 'Los Angeles Intl', unlocode: 'LAX', country: 'US', type: 'airport' },
  { name: 'JFK (New York)', unlocode: 'JFK', country: 'US', type: 'airport' },
  { name: 'Schiphol (Amsterdam)', unlocode: 'AMS', country: 'NL', type: 'airport' },
  { name: 'Charles de Gaulle (Paris)', unlocode: 'CDG', country: 'FR', type: 'airport' },
  { name: 'Heathrow (London)', unlocode: 'LHR', country: 'GB', type: 'airport' },
];

export function findPortByTerm(term: string): Port | undefined {
    const searchTerm = term.toLowerCase().split(',')[0].trim();
    if (!searchTerm) return undefined;
    return portsAndAirports.find(p => p.name.toLowerCase() === searchTerm || p.unlocode.toLowerCase() === searchTerm);
}
